### ISSUE TITLE
Linked issues ?

### ISSUE THREAD

**Issue by franky47** [rburgst/fastify-jest-timers#1]
Hi, I've ended up in the same situation, do you have a backlink to an issue or discussion on this topic ? Thanks!

FYI, I've fixed my tests by using the `jest.useFakeTimers('legacy')` implementation rather than the `'modern'` default.

**Comment by rburgst** [comment]
https://github.com/facebook/jest/issues/12056

**Comment by rburgst** [comment]
For me the solution was overwriting Date.now. Legacy timers didn't work for me.

**Comment by franky47** [comment]
Thank you!
